remote_theme: pages-themes/minimal@v0.2.0
title: Kevin Spring's portfolio
descriptoin: Data Analytics | Biology | Agriculture
plugins:
- jekyll-remote-theme
logo: /assets/img/logo.jpg
show_downloads: false
